package models.reserves

import org.pillarone.riskanalytics.core.output.AggregatedCollectingModeStrategy

model=models.reserves.ReservesModel
displayName='Reserved Claims'

components.claimsGenerators.subsubcomponents.outClaimsLeanDevelopment=AggregatedCollectingModeStrategy.IDENTIFIER
components.claimsGenerators.outClaimsLeanDevelopment=AggregatedCollectingModeStrategy.IDENTIFIER
components.reserveGenerators.subsubcomponents.outClaimsLeanDevelopment=AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.subcontracts.outClaimsDevelopmentLeanNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.subcontracts.outClaimsDevelopmentLeanCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.subcontracts.outClaimsDevelopmentLeanGross=AggregatedCollectingModeStrategy.IDENTIFIER
