package models.dependency

import org.pillarone.riskanalytics.core.output.AggregatedCollectingModeStrategy

model=models.dependency.TwoLobDependencyModel
displayName='All possible output'

components.frequencyGeneratorEvent.outFrequency=AggregatedCollectingModeStrategy.IDENTIFIER
components.frequencyGeneratorLarge.outFrequency=AggregatedCollectingModeStrategy.IDENTIFIER
components.independentFrequencyGeneratorFire.outFrequency=AggregatedCollectingModeStrategy.IDENTIFIER
components.independentFrequencyGeneratorHull.outFrequency=AggregatedCollectingModeStrategy.IDENTIFIER
components.cxl.outCoveredClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.cxl.outUncoveredClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.hull.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.hull.subEventClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.hull.subSingleClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.hull.subAttritionalClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.hull.subEventSeverityExtractor.outSeverities=AggregatedCollectingModeStrategy.IDENTIFIER
components.hull.subSingleSeverityExtractor.outProbabilities=AggregatedCollectingModeStrategy.IDENTIFIER
components.hull.subAttritionalSeverityExtractor.outProbabilities=AggregatedCollectingModeStrategy.IDENTIFIER
components.fire.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.fire.subEventClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.fire.subSingleClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.fire.subAttritionalClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.fire.subEventSeverityExtractor.outSeverities=AggregatedCollectingModeStrategy.IDENTIFIER
components.fire.subSingleSeverityExtractor.outProbabilities=AggregatedCollectingModeStrategy.IDENTIFIER
components.fire.subAttritionalSeverityExtractor.outProbabilities=AggregatedCollectingModeStrategy.IDENTIFIER
components.claimsAggregator.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.claimsAggregator.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.claimsAggregator.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
