package models.reinsuranceComparison

import org.pillarone.riskanalytics.core.output.AggregatedCollectingModeStrategy

model=models.reinsuranceComparison.ReinsuranceComparisonModel

components.mtpl.subRiProgramA.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramA.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramA.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramB.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramB.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramB.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramC.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramC.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramC.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramD.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramD.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramD.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramA.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramA.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramA.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramB.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramB.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramB.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramC.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramC.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramC.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramD.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramD.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgramD.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramA.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramA.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramA.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramB.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramB.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramB.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramC.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramC.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramC.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramD.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramD.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgramD.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramA.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramA.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramA.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramB.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramB.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramB.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramC.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramC.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramC.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramD.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramD.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgramD.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER