package models.reinsuranceComparison

import org.pillarone.riskanalytics.core.output.AggregatedCollectingModeStrategy

model = ReinsuranceComparisonModel

components.mtpl.subRiProgramA.subContract1.outCoverUnderwritingInfo=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramA.subContract1.outNetAfterCoverUnderwritingInfo=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramA.subContract1.outCoveredClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramA.subContract1.outUncoveredClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramA.outUnderwritingInfoCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramA.outUnderwritingInfoGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgramA.outUnderwritingInfoNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subUnderwriting.outUnderwritingInfo=AggregatedCollectingModeStrategy.IDENTIFIER
