package models.singleLob

import org.pillarone.riskanalytics.core.output.AggregatedCollectingModeStrategy

model=models.singleLob.SingleLobMultiClaimsGeneratorModel
displayName='Result Collector'

components.mtpl.subClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subClaimsGenerator.subSingleClaimsGenerator1.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subClaimsGenerator.subSingleClaimsGenerator2.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subClaimsGenerator.subSingleClaimsGenerator3.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subClaimsGenerator.subSingleClaimsGenerator4.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subClaimsGenerator.subSingleClaimsGenerator5.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subClaimsGenerator.subSingleClaimsGenerator6.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subClaimsGenerator.subSingleClaimsGenerator7.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
