package models.finiteRe

import org.pillarone.riskanalytics.core.output.AggregatedCollectingModeStrategy

model=models.finiteRe.FiniteReModel
displayName='EAB, Claims (aggregated)'
components.claimsGenerators.subsubcomponents.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.claimsGenerators.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.wholeAccountStopLoss.outCoveredClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.wholeAccountStopLoss.outFilteredClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.finiteRe.outExperienceAccount=AggregatedCollectingModeStrategy.IDENTIFIER
components.finiteRe.outReinsurance=AggregatedCollectingModeStrategy.IDENTIFIER
components.lineOfBusinessReinsurance.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.lineOfBusinessReinsurance.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.lineOfBusinessReinsurance.subcontracts.outCoveredClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.lineOfBusinessReinsurance.subcontracts.outFilteredClaims=AggregatedCollectingModeStrategy.IDENTIFIER