package models.capitalEagle

import org.pillarone.riskanalytics.core.output.AggregatedCollectingModeStrategy

model=models.capitalEagle.CapitalEagleModel
displayName = 'Reports'

components.mtpl.subRiProgram.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgram.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgram.outUnderwritingInfoCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgram.outUnderwritingInfoGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgram.outUnderwritingInfoNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subClaimsGenerator.subAttritionalClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subClaimsGenerator.subSingleClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgram.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgram.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgram.outUnderwritingInfoCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgram.outUnderwritingInfoGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgram.outUnderwritingInfoNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subClaimsGenerator.subAttritionalClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subClaimsGenerator.subSingleClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgram.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgram.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgram.outUnderwritingInfoCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgram.outUnderwritingInfoGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgram.outUnderwritingInfoNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subClaimsGenerator.subAttritionalClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subClaimsGenerator.subSingleClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgram.outClaimsGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgram.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgram.outUnderwritingInfoCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgram.outUnderwritingInfoGross=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgram.outUnderwritingInfoNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subClaimsGenerator.subAttritionalSeverityClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subClaimsGenerator.subEQGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subClaimsGenerator.subFloodGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subClaimsGenerator.subSingleClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subClaimsGenerator.subStormGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER