package models.capitalEagle

import org.pillarone.riskanalytics.core.output.AggregatedCollectingModeStrategy

model=models.capitalEagle.CapitalEagleModel
displayName = 'Claims and Premium per Line (DB Batch Insert)'

components.mtpl.subRiProgram.outUnderwritingInfoCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgram.outUnderwritingInfoNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgram.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subRiProgram.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.mtpl.subUnderwriting.outUnderwritingInfo=AggregatedCollectingModeStrategy.IDENTIFIER

components.motorHull.subClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgram.outUnderwritingInfoCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgram.outUnderwritingInfoNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgram.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subRiProgram.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.motorHull.subUnderwriting.outUnderwritingInfo=AggregatedCollectingModeStrategy.IDENTIFIER

components.personalAccident.subClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgram.outUnderwritingInfoCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgram.outUnderwritingInfoNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgram.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subRiProgram.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.personalAccident.subUnderwriting.outUnderwritingInfo=AggregatedCollectingModeStrategy.IDENTIFIER

components.property.subClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgram.outUnderwritingInfoCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgram.outUnderwritingInfoNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgram.outClaimsCeded=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subRiProgram.outClaimsNet=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subUnderwriting.outUnderwritingInfo=AggregatedCollectingModeStrategy.IDENTIFIER
components.property.subClaimsGenerator.outClaims=AggregatedCollectingModeStrategy.IDENTIFIER
