package models.podraP

import org.pillarone.riskanalytics.core.output.AggregatedCollectingModeStrategy

model = models.podraP.PodraPModel
displayName = "Reinsurance Contracts Details"

components.underwritingSegments.subunderwritingSegments.outUnderwritingInfo = AggregatedCollectingModeStrategy.IDENTIFIER
components.underwritingSegments.outUnderwritingInfo = AggregatedCollectingModeStrategy.IDENTIFIER
components.claimsGenerators.outClaims = AggregatedCollectingModeStrategy.IDENTIFIER
components.claimsGenerators.subsubcomponents.outClaims = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.outClaimsCeded = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.outClaimsGross = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.outClaimsNet = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.subContracts.subriContracts.outCoveredClaims = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.subContracts.subriContracts.outFilteredClaims = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.subContracts.subriContracts.outUncoveredClaims = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.subContracts.subriContracts.outCoverUnderwritingInfo = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.subContracts.subriContracts.outFilteredUnderwritingInfo = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.subContracts.subriContracts.outNetAfterCoverUnderwritingInfo = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.outCoverUnderwritingInfo = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.outNetAfterCoverUnderwritingInfo = AggregatedCollectingModeStrategy.IDENTIFIER
components.reinsurance.outUnderwritingInfo = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.outClaimsCeded = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.outClaimsGross = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.outClaimsNet = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.outUnderwritingInfoCeded = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.outUnderwritingInfoGross = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.outUnderwritingInfoNet = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.sublineOfBusiness.outClaimsCeded = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.sublineOfBusiness.outClaimsGross = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.sublineOfBusiness.outClaimsNet = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.sublineOfBusiness.outUnderwritingInfoCeded = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.sublineOfBusiness.outUnderwritingInfoGross = AggregatedCollectingModeStrategy.IDENTIFIER
components.linesOfBusiness.sublineOfBusiness.outUnderwritingInfoNet = AggregatedCollectingModeStrategy.IDENTIFIER
